### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by redsigma** [DanielOrtez/RuneBook#2]
![image](https://user-images.githubusercontent.com/20425476/82488406-8274bc00-9ae8-11ea-9275-f1ce54008aa1.png)
So according to the image above. It wont let me type any char manually. I am connected to the client, because at the bottom it shows the last active mastery. 
I have tried a full reinstall, removed appdata folder too, and reinstall again but still no change.

Can you make it so it works offline too, even if the list of chars it's not updated to the latest. Or if you can tell me where to find the log files or a way to reset it

**Comment by vitaliyrahmanin** [comment]
Also

**Comment by DanielOrtez** [comment]
Hi, guys. 
Right now I'm swamped with work, but as soon as I'm free I'll try to fix it.

**Comment by DanielOrtez** [comment]
problem fixed in v1.0.2
